name: calculator_domain_starter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.1.4
  flutter: 3.13.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  provider: ^6.1.2

  feature_calculator:
    path: ../../feature/calculator/target/junewoov

dev_dependencies:
  flutter_lints: 3.0.1
