name: calculator_domain_starter_di
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.1.4
  flutter: 3.13.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  provider: ^6.1.2

  calculator_domain_starter_domain:
    path: ../domain

  calculator_domain_starter_data:
    path: ../data

  calculator_domain_starter_presentation:
    path: ../presentation

dev_dependencies:
  flutter_lints: 3.0.1
